task:
  matrix:
    - name: linux
      container:
        dockerfile: .ci/Dockerfile
      debian_test_script: cargo test --all-features
    - name: macos
      macos_instance:
        image: ghcr.io/cirruslabs/macos-monterey-base:latest
      env:
        PATH: $PATH:$HOME/.cargo/bin
      install_script: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      install_audit_script: cargo install cargo-audit
      add_clippy_fmt_script: rustup component add clippy && rustup component add rustfmt
      macos_test_script: cargo test

  registry_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat Cargo.lock
  target_cache:
    folder: target
    fingerprint_script:
      - rustc --version
      - cat Cargo.lock
  build_script: cargo build
  security_script: cargo audit
  format_script: cargo fmt --all -- --check
  lint_script: cargo clippy -- -D warnings
  before_cache_script: rm -rf $CARGO_HOME/registry/index
