task:
  matrix:
    - name: linux
      container:
        image: rust:latest
      prebuild_script: sudo apt install libdbus-1-dev pkgconf-pkg-config
    - name: macos
      macos_instance:
        image: ghcr.io/cirruslabs/macos-monterey-base:latest
      env:
        PATH: $PATH:$HOME/.cargo/bin
      install_script: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

  registry_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat Cargo.lock
  target_cache:
    folder: target
    fingerprint_script:
      - rustc --version
      - cat Cargo.lock
  build_script: cargo build
  test_script: cargo test
  before_cache_script: rm -rf $CARGO_HOME/registry/index
