task:
  matrix:
    - name: linux
      container:
        image: rust:latest
      prebuild_script:
        - apt update
        - apt install libdbus-1-dev pkg-config -y
      debian_test_script: cargo test --all-features
    - name: macos
      macos_instance:
        image: ghcr.io/cirruslabs/macos-monterey-base:latest
      env:
        PATH: $PATH:$HOME/.cargo/bin
      install_script: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      macos_test_script: cargo test

  registry_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat Cargo.lock
  target_cache:
    folder: target
    fingerprint_script:
      - rustc --version
      - cat Cargo.lock
  build_script: cargo build
  security_script:
    - cargo install cargo-audit
    - cargo audit
  format_script: cargo fmt --all -- --check
  lint_script:
    - rustup component add clippy
    - cargo clippy -- -D warnings
  before_cache_script: rm -rf $CARGO_HOME/registry/index
