#! ../target/release/trun

["TEST 1"]
name = "ENABLE SSHD"
state = "Enabled"
service = "sshd"
["TEST 2"]
name = "START SSHD"
state = "Started"
service = "sshd"
["TEST 3"]
name = "STOP SSHD"
state = "Stopped"
service = "sshd"
["TEST 4"]
name = "DISABLE SSHD"
state = "Disabled"
service = "sshd"
["TEST 5"]
name = "Start SSHD"
state = "Started"
service = "sshd"
enabled = true
