["TEST BLOCK"]
module = "BlockInFile"
name = "Add Hello Block"
block = """
fn main() {
    println!("Hello from TRUN");
}
"""
signature = "MOHEEB"
comment = "//"
file = "./hello_world.rs"



["Test APT"]
module = "Apt"
name = "Install Apt"
app = "apt"
state = "Present"
panics = false

["TEST PROMPT"]
module = "Prompt"
name = "Prompt Test"
command = "echo hello"
strict = true
message = "Are you Sure you want to print hello?"
answer = ["Yes","No"]

